#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

fail() {
  printf 'FAIL: %s\n' "$*" >&2
  exit 1
}

head -1 AGENTS.md | grep -q '^<!-- GENERATED by ~/.agents/bin/agents-sync' &&
  fail 'AGENTS.md still has generated banner'

if grep -Eq '\.agents/(core|rules|hooks)(/|`|$)' AGENTS.md hooks.json; then
  fail 'active config still references .agents control plane'
fi

jq -e '
  .hooks.PreToolUse[]?.hooks[]?
  | select(.command == "bash \"$HOME/.codex/hooks/guard-codex-git-push.sh\"")
' hooks.json >/dev/null || fail 'Codex-local git guard path missing'

jq -e '
  .hooks.SessionStart[]?.hooks[]?
  | select(.command == "bash \"$HOME/.codex/hooks/drift-check.sh\"")
' hooks.json >/dev/null || fail 'Codex-local drift check path missing'

for file in hooks/guard-codex-git-push.sh hooks/guard-git-push.sh hooks/drift-check.sh rules/default.rules; do
  [ -f "$file" ] || fail "local file missing: $file"
done
for rule in cookbook cpp dotnet frontend-spa infra testing typescript winforms; do
  [ -f "rules/$rule.md" ] || fail "local stack rule missing: rules/$rule.md"
done

bytes=$(wc -c < AGENTS.md | tr -d ' ')
[ "$bytes" -le 5000 ] || fail "AGENTS.md exceeds thin budget: ${bytes}B"
[ "$bytes" -lt 4500 ] || fail "AGENTS.md must stay below 90% of its 5000B budget: ${bytes}B"

for marker in 'Tier 0 hard rules' dev-workflow 'Codex adapter' context7-mcp; do
  grep -Fq "$marker" AGENTS.md || fail "thin kernel marker missing: $marker"
done

grep -Eq '~/.agents/skills/dev-workflow/SKILL\.md' AGENTS.md ||
  fail 'shared dev-workflow route missing'

grep -Fqx -- '- Delegation：依 shared `dev-workflow` [INT-4] 由 AI 自主判定，無須另問。' AGENTS.md ||
  fail 'Codex delegation adapter must stay thin and point to shared INT-4'

if grep -Eq 'resolve-library-id|query-docs|^### S[456]|bin/pr-review-gate' AGENTS.md; then
  fail 'AGENTS.md duplicates skill-owned procedure'
fi

grep -Fq '~/.agents/bin/agents-branch' AGENTS.md ||
  fail 'verified agents-branch path missing'

# [S5-3]（~/.agents/skills/dev-workflow/SKILL.md）要求 house over-engineering baseline 兩條
# 逐字進「每一個」reviewer prompt，含 host-local review agent。Codex 的兩個 .toml 是 Claude
# 側同名 agent 的鏡像；2026-08-03 A1 首次注入時只補了 Claude 側，導致同一個 reviewer 在兩台
# host 行為不同——[S5-3] 是 shared kernel rule，逐 host 補到一半等於沒補。
# closed-world set 而非 pattern 過濾，理由同 ~/.claude/tests/repo-integrity.sh 的同名斷言：
# 檔名 glob 會讓 `security-reviewer` 這類真 code reviewer 靜默漏掉（fail-open）。
# 比對兩條全文而非英文 label：[S5-3] 驗證條款寫的是「含該兩條全文」。
s53_agents='agents/code-reviewer.toml agents/DotNet-Code-Reviewer.toml'
actual_toml="$(git ls-files 'agents/*.toml' | LC_ALL=C sort | tr '\n' ' ')"
expected_toml="$(printf '%s' "$s53_agents" | tr ' ' '\n' | LC_ALL=C sort | tr '\n' ' ')"
[ "$actual_toml" = "$expected_toml" ] ||
  fail "agents/ 清單已變動，[S5-3] 分類需更新：實際=[$actual_toml] 已分類=[$expected_toml]"
for f in $s53_agents; do
  [ -f "$f" ] || fail "[S5-3] 分類指向不存在的 agent: $f"
  if grep -Fq '手刻標準庫或平台已提供的功能' "$f" &&
    grep -Fq '為平台／既有模組已有的能力新增依賴' "$f"; then
    :
  else
    fail "code review agent 缺 [S5-3] over-engineering baseline 兩條全文: $f"
  fi
done

grep -Eq 'bash tests/global-config-ownership\.sh' .github/workflows/ci.yml ||
  fail 'global ownership test missing from CI'

if grep -Eq '^# tier[12]|superpowers:|mp-(diagnose|grill-with-docs|improve-codebase-architecture|tdd)' AGENTS.md; then
  fail 'AGENTS.md still contains legacy/non-thin workflow'
fi

grep -Fq 'blanket authorization' AGENTS.md &&
  fail 'shared authorization semantics leaked into Codex adapter'

if [ "${CI:-}" = true ] && [ ! -f config.toml ]; then
  printf 'SKIP: ignored live config.toml is unavailable in CI; local host canary remains mandatory\n'
elif [ ! -f config.toml ]; then
  fail 'live config.toml missing; cannot verify Context7 policy'
elif python3 - "$PWD/config.toml" <<'PY'
import sys, tomllib
with open(sys.argv[1], "rb") as f:
    context7 = tomllib.load(f)["mcp_servers"]["context7"]
assert context7["enabled"] is True
assert context7["command"] == "npx"
assert context7["args"][-1] == "@upstash/context7-mcp@3.2.5"
assert context7["enabled_tools"] == ["resolve-library-id", "query-docs"]
assert context7["default_tools_approval_mode"] == "auto"
PY
then
  :
else
  fail 'Context7 must be pinned, exact-tool scoped, and auto-approved'
fi

# CONVENTIONS 規則 11 的 host 一側。必須用 find 不得用 ls + glob：後者在 zsh 下任一目錄
# 無匹配即 nomatch 中止並回 0＝假合規（2026-07-30 實測同指令 zsh 回 0、bash 回 4）。
# dotfile 排除＝規則 11 的「app 自管 runtime state 備份」例外（.codex-global-state.json.bak）。
manual_bak="$(find . -maxdepth 1 -name '*.bak*' -not -name '.*' 2>/dev/null | tr '\n' ' ')"
[ -z "$manual_bak" ] || fail "manual .bak present (CONVENTIONS rule 11): $manual_bak"

# hooks/drift-check.sh 若呼叫共用的 parity checker，必須先以 [ -x ] 守護——那支 helper 在
# ~/.agents 未 clone 或該變更未 merge 時不存在，無守護會讓 SessionStart 噴錯。這條放本
# repo 而非 ~/.agents 的 test：drift-check.sh 是本 repo 擁有的檔（ownership 邊界）。
if grep -q 'bash "\$HOME/\.agents/bin/hook-parity-check"' hooks/drift-check.sh 2>/dev/null; then
  grep -q '\[ -x "\$HOME/\.agents/bin/hook-parity-check" \]' hooks/drift-check.sh ||
    fail 'parity checker invocation lacks [ -x ] guard'
fi

printf 'PASS: Codex global config ownership\n'
